In [45]:
import pandas as pd

pd.set_option("display.max_rows", 100)   # or None for unlimited
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 20)

In [46]:
filename = "WorkingWithDates.csv"

In [47]:
df = pd.read_csv(filename)
df.head()

  Team              Date Home_Away  Opp   W/L  W-L   Date_Clean
0  BAL  Thursday, Mar 29      Home  MIN  W-wo  1-0  Mar 29 2018
1  BAL  Saturday, Mar 31      Home  MIN     L  1-1  Mar 31 2018
2  BAL     Sunday, Apr 1      Home  MIN     L  1-2   Apr 1 2018
3  BAL     Monday, Apr 2         @  HOU     L  1-3   Apr 2 2018
4  BAL    Tuesday, Apr 3         @  HOU     L  1-4   Apr 3 2018

In [48]:
df.dtypes

Team          object
Date          object
Home_Away     object
Opp           object
W/L           object
W-L           object
Date_Clean    object
dtype: object

## Importing with a Datetime Column

In [49]:
df = pd.read_csv(filename, parse_dates=["Date"])  # Throws a UserWarning since Date is not in a common datetime format
df.dtypes

C:\Users\domin\AppData\Local\Temp\ipykernel_11660\2583362749.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(filename, parse_dates=["Date"])  # Throws a UserWarning since Date is not in a common datetime format

Team          object
Date          object
Home_Away     object
Opp           object
W/L           object
W-L           object
Date_Clean    object
dtype: object

In [50]:
df = pd.read_csv(filename, parse_dates=["Date_Clean"]) # Date_Clean is already in a common datetime format
df.dtypes

Team                  object
Date                  object
Home_Away             object
Opp                   object
W/L                   object
W-L                   object
Date_Clean    datetime64[ns]
dtype: object

## Formatting a Datetime Column

In [51]:
# Convert the Date_Clean column to datetime format and assign it to a new column called Date
df['Date'] = pd.to_datetime(df['Date_Clean'], format='%b %d %Y')
df.dtypes

Team                  object
Date          datetime64[ns]
Home_Away             object
Opp                   object
W/L                   object
W-L                   object
Date_Clean    datetime64[ns]
dtype: object

In [52]:
df.drop(columns=['Date_Clean'], inplace=True)
df.head(5)

  Team       Date Home_Away  Opp   W/L  W-L
0  BAL 2018-03-29      Home  MIN  W-wo  1-0
1  BAL 2018-03-31      Home  MIN     L  1-1
2  BAL 2018-04-01      Home  MIN     L  1-2
3  BAL 2018-04-02         @  HOU     L  1-3
4  BAL 2018-04-03         @  HOU     L  1-4

## Extracting Datetime Values

In [53]:
# Retrieve the month, day, year, day of week, quarter, and weekday number from the Date column
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Year'] = df['Date'].dt.year
df['DayOfWeek'] = df['Date'].dt.day_name()
df['Quarter'] = df['Date'].dt.quarter
df['WeekdayNumber'] = df['Date'].dt.weekday

In [54]:
df.head(10)

,Team,Date,Home_Away,Opp,W/L,W-L,Month,Day,Year,DayOfWeek,Quarter,WeekdayNumber
0,BAL,2018-03-29,Home,MIN,W-wo,1-0,3,29,2018,Thursday,1,3
1,BAL,2018-03-31,Home,MIN,L,1-1,3,31,2018,Saturday,1,5
2,BAL,2018-04-01,Home,MIN,L,1-2,4,1,2018,Sunday,2,6
3,BAL,2018-04-02,@,HOU,L,1-3,4,2,2018,Monday,2,0
4,BAL,2018-04-03,@,HOU,L,1-4,4,3,2018,Tuesday,2,1
5,BAL,2018-04-04,@,HOU,L,1-5,4,4,2018,Wednesday,2,2
6,BAL,2018-04-05,@,NYY,W,2-5,4,5,2018,Thursday,2,3
7,BAL,2018-04-06,@,NYY,W,3-5,4,6,2018,Friday,2,4
8,BAL,2018-04-07,@,NYY,L,3-6,4,7,2018,Saturday,2,5
9,BAL,2018-04-08,@,NYY,W,4-6,4,8,2018,Sunday,2,6

## Grouped Chronological Sortation

In [55]:
# Chronologically sort the data by FeatureName and Date, then reset the index
featureName = 'Team'
df = df.sort_values([featureName, 'Date']).reset_index(drop=True)
df.tail(10)

,Team,Date,Home_Away,Opp,W/L,W-L,Month,Day,Year,DayOfWeek,Quarter,WeekdayNumber
4822,WSN,2018-09-18,@,MIA,W,77-75,9,18,2018,Tuesday,3,1
4823,WSN,2018-09-20,Home,NYM,L,77-76,9,20,2018,Thursday,3,3
4824,WSN,2018-09-21,Home,NYM,L,77-77,9,21,2018,Friday,3,4
4825,WSN,2018-09-22,Home,NYM,W,78-77,9,22,2018,Saturday,3,5
4826,WSN,2018-09-23,Home,NYM,L,78-78,9,23,2018,Sunday,3,6
4827,WSN,2018-09-24,Home,MIA,W,79-78,9,24,2018,Monday,3,0
4828,WSN,2018-09-25,Home,MIA,W,80-78,9,25,2018,Tuesday,3,1
4829,WSN,2018-09-26,Home,MIA,W,81-78,9,26,2018,Wednesday,3,2
4830,WSN,2018-09-28,@,COL,L,81-79,9,28,2018,Friday,3,4
4831,WSN,2018-09-29,@,COL,W,82-79,9,29,2018,Saturday,3,5

## Filtering Before or After Specific Dates

In [56]:
# Filtering After a Certain Date
df_post_april = df[df['Date'] >= '2018-05-01'].reset_index(drop=True)
df_post_april.head(10)

,Team,Date,Home_Away,Opp,W/L,W-L,Month,Day,Year,DayOfWeek,Quarter,WeekdayNumber
0,ARI,2018-05-01,Home,LAD,W,21-8,5,1,2018,Tuesday,2,1
1,ARI,2018-05-02,Home,LAD,L,21-9,5,2,2018,Wednesday,2,2
2,ARI,2018-05-03,Home,LAD,L,21-10,5,3,2018,Thursday,2,3
3,ARI,2018-05-04,Home,HOU,L,21-11,5,4,2018,Friday,2,4
4,ARI,2018-05-05,Home,HOU,W-wo,22-11,5,5,2018,Saturday,2,5
5,ARI,2018-05-06,Home,HOU,W,23-11,5,6,2018,Sunday,2,6
6,ARI,2018-05-08,@,LAD,W,24-11,5,8,2018,Tuesday,2,1
7,ARI,2018-05-09,@,LAD,L,24-12,5,9,2018,Wednesday,2,2
8,ARI,2018-05-10,Home,WSN,L,24-13,5,10,2018,Thursday,2,3
9,ARI,2018-05-11,Home,WSN,L,24-14,5,11,2018,Friday,2,4

In [57]:
# Filtering Before a Certain Date
df_pre_april = df[df['Date'] < '2018-04-01'].reset_index(drop=True)
df_pre_april.head(10)

,Team,Date,Home_Away,Opp,W/L,W-L,Month,Day,Year,DayOfWeek,Quarter,WeekdayNumber
0,ARI,2018-03-29,Home,COL,W,1-0,3,29,2018,Thursday,1,3
1,ARI,2018-03-30,Home,COL,W,2-0,3,30,2018,Friday,1,4
2,ARI,2018-03-31,Home,COL,L,2-1,3,31,2018,Saturday,1,5
3,ATL,2018-03-29,Home,PHI,W-wo,1-0,3,29,2018,Thursday,1,3
4,ATL,2018-03-30,Home,PHI,L,1-1,3,30,2018,Friday,1,4
5,ATL,2018-03-31,Home,PHI,W,2-1,3,31,2018,Saturday,1,5
6,BAL,2018-03-29,Home,MIN,W-wo,1-0,3,29,2018,Thursday,1,3
7,BAL,2018-03-31,Home,MIN,L,1-1,3,31,2018,Saturday,1,5
8,BOS,2018-03-29,@,TBR,L,0-1,3,29,2018,Thursday,1,3
9,BOS,2018-03-30,@,TBR,W,1-1,3,30,2018,Friday,1,4